[workspace]
git_only = true
publish = false
release = false
release_always = false
git_release_enable = false
git_tag_name = "v{{ version }}"
semver_check = false
dependencies_update = false
pr_labels = ["release"]
pr_branch_prefix = "release-plz-"
repo_url = "https://github.com/NewComer00/Chobits"

[[package]]
name = "chobits"
release = true
changelog_path = "../../CHANGELOG.md"
